import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { isAuthenticated } from "./api/isAuthenticated";
import MemoNav from "@/components/memo-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await isAuthenticated();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {session ? (
          <div className="flex justify-around">
            <MemoNav />
            {children}
          </div>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  );
}
